# Generated by Django 6.0.4 on 2026-06-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default/avatar.png', null=True, upload_to='profiles/avatars/', verbose_name='avatar'),
        ),
    ]
