# Generated by Django 6.0.4 on 2026-05-21 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent', models.CharField(max_length=10, unique=True, verbose_name='patent')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patent'], name='vehicle_patent_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('detail', models.TextField(verbose_name='detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_logs', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'vehicle log',
                'verbose_name_plural': 'vehicle logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vehicle_logs/%Y/%m/%d/', verbose_name='file')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10, verbose_name='type')),
                ('vehicle_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='vehicles.vehiclelog', verbose_name='vehicle log')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclelog',
            index=models.Index(fields=['vehicle', '-created_at'], name='vehiclelog_vehicle_date_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['vehicle_log', 'type'], name='media_log_type_idx'),
        ),
    ]
