# Generated by Django 6.0.4 on 2026-05-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='type',
            field=models.CharField(choices=[('incident', 'Incident'), ('maintenance', 'Maintenance'), ('observation', 'Observation'), ('cleaning', 'Cleaning')], default='observation', max_length=30),
        ),
    ]
