# Generated by Django 6.0.4 on 2026-06-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclelog_status_vehiclelog_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'permissions': [('search_vehicle_by_patent', 'Can search vehicle by patent')], 'verbose_name': 'vehicle', 'verbose_name_plural': 'vehicles'},
        ),
    ]
