# Generated by Django 6.0.4 on 2026-06-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclelog',
            options={'ordering': ['-created_at'], 'permissions': [('update_vehiclelog_status', 'Can change vehicle log status')], 'verbose_name': 'vehicle log', 'verbose_name_plural': 'vehicle logs'},
        ),
    ]
