# Generated by Django 6.0.4 on 2026-06-29 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehiclelog_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(help_text='The uploaded file. Supported formats are typically images (JPEG, PNG) or videos (MP4, MOV).', upload_to='vehicle_logs/%Y/%m/%d/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('photo', 'photo'), ('video', 'video')], help_text='The format category of the file, determining how it should be rendered in the interface.', max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='media',
            name='vehicle_log',
            field=models.ForeignKey(help_text='The specific vehicle log entry this media file is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='vehicles.vehiclelog', verbose_name='vehicle log'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(help_text='The commercial name of the vehicle manufacturer (e.g., Toyota, Chevrolet, Ford).', max_length=100, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically recorded by the system when this vehicle entry is created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(help_text='The specific commercial model or series name of the vehicle (e.g., Corolla, Sail, F-150).', max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='patent',
            field=models.CharField(help_text='Chilean format consisting of 4 letters and 2 numbers (e.g., ABCD12) without hyphens.', max_length=10, unique=True, verbose_name='patent'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='The 4-digit manufacturing or model year of the vehicle (e.g., 2024).', verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp automatically recorded when this log entry was generated.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='created_by',
            field=models.ForeignKey(help_text='The user account that recorded this log entry. Automatically cleared if the user is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_logs', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='detail',
            field=models.TextField(help_text='A comprehensive description of the event, work performed, or observations made.', verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', help_text='The current operational state of this log entry (e.g., Pending, Resolved or Reviewed).', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='title',
            field=models.CharField(help_text='A brief summary or headline of the log event (e.g., Routine Oil Change, Brake Noise Issue).', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='type',
            field=models.CharField(choices=[('incident', 'Incident'), ('maintenance', 'Maintenance'), ('observation', 'Observation'), ('cleaning', 'Cleaning')], default='observation', help_text='The category of the log entry to help classify the record (e.g., Maintenance, Observation, Incident or Cleaning).', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiclelog',
            name='vehicle',
            field=models.ForeignKey(help_text='The vehicle this log entry is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vehicles.vehicle', verbose_name='vehicle'),
        ),
    ]
