# Generated by Django 6.0.4 on 2026-05-23 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('SELLER', 'Seller'), ('VIEWER', 'Viewer')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('SELLER', 'Seller'), ('VIEWER', 'Viewer')], help_text='Role of the user within the company', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this membership is active.', verbose_name='is active')),
                ('invited_at', models.DateTimeField(blank=True, help_text='Date when the user was invited to the company', null=True, verbose_name='invited at')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Date when the user joined the company', verbose_name='joined at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['user'], name='memberships_user_id_f9f114_idx'), models.Index(fields=['role'], name='memberships_role_582366_idx'), models.Index(fields=['is_active'], name='memberships_is_acti_c31b58_idx')],
            },
        ),
    ]
