# Generated by Django 6.0.4 on 2026-05-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='membership',
            name='memberships_role_582366_idx',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
    ]
