# Generated by Django 6.0.4 on 2026-06-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_remove_membership_memberships_role_582366_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
